### DISCUSSION TITLE
Add MB0 (3 phase) Inverters

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [JensenNick/huawei_solar_pees#47] [Forum]
Hi @JensenNick 

Just trying to add the new range of MB0 Hybrid 3 phase inverters into PEES, but wondering how you'd prefer to hand it.
I've currently followed the current way and added ' inverter_1_operating_voltage_mb0' that ties in with them having a higher 200-1000 operating range. 

This then however means that the input_card.md would need to either have the toggle for the 3phase inverters made 'generic', as it currently refers to the 'M1' range specifically and additionally would neeed the resultant conditional card that brings up the 3p operating voltage slider to be reworked to add the ability to show the MB0 (200-1000V with a default of 600V) instead of the currently option of the M1 (140-980V range).

Here is a quick draft edit:

```
# ----------------------------------------
# HUAWEI SOLAR INPUT - User Specific Input
# ----------------------------------------
# version: v1.0.2
# branch: main
# domain: https://github.com/JensenNick/huawei_solar_pees
# codeowner: Nick Jensen
#
# This is the optional "Huawei Solar PEES Input package" which is used to save your
# specific solar PV settings for the efficiency corrected power input sensor. This
# package can only be used along with the "Huawei Solar PEES package" and the code
# for the Lovelace card. The package allow you to save your specific solar PV settings
# between updates of the "Huawei Solar PEES package". If you do not use the "Efficiency
# Corrected Input Power Sensor" you do not need to do anything.
#
# You add your specific solar PV settings for the "Efficiency Corrected Input Power
# Sensor" in the Lovelace card. The efficiency corrected input power sensor has been
# implemented in the "Huawei Solar PEES package" so you do not need to copy/paste it
# from the Wiki Pages.
#
# You should only make changes in the Lovelace card, not in the code below. Advanced
# users can adjust the input_numbers, min, "max and step to their liking, but be aware
# of the impact that these input numbers have. Please refer to the Wiki Pages
#
# You still need to edit your input sensors in the huawei_solar_pees.yaml file if your
# input sensors do not match the ones used by default.
#
# -----------
# AUTOMATIONS
# -----------
automation:
  ## ------------------------------
  ## Switch Inverter Between Phases
  - alias: "Switch Inverter #1 to 1phase"
    trigger:
      platform: state
      entity_id: input_boolean.inverter_1_1phase
      to: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.inverter_1_3phase
    mode: single
  - alias: "Switch Inverter #1 to 3 Phase"
    trigger:
      platform: state
      entity_id: input_boolean.inverter_1_3phase
      to: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.inverter_1_1phase
  - alias: "Switch Inverter #2 to 1phase"
    trigger:
      platform: state
      entity_id: input_boolean.inverter_2_1phase
      to: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_3phase
    mode: single
  - alias: "Switch Inverter #2 to 3 Phase"
    trigger:
      platform: state
      entity_id: input_boolean.inverter_2_3phase
      to: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_1phase
# -------------
# INPUT BOOLEAN
# -------------
input_boolean:
  inverter_1_1phase:
    name: "Inverter #1 1phase"
  inverter_1_3phase:
    name: "Inverter #1 3phase"
  inverter_2_1phase:
    name: "Inverter #2 1phase"
  inverter_2_3phase:
    name: "Inverter #2 3phase"
# ------------
# INPUT NUMBER
# ------------
input_number:
  ## --------------------
  ## Inverter #1 Settings
  inverter_1_operating_voltage_l1:
    name: "Inverter #1 Operating Voltage L1"
    min: 90
    max: 560
    initial: 360
    step: 5
  inverter_1_operating_voltage_m1:
    name: "Inverter #1 Operating Voltage M1"
    min: 140
    max: 980
    initial: 600
    step: 5
  inverter_1_operating_voltage_mb0:
    name: "Inverter #1 Operating Voltage MB0"
    min: 200
    max: 1000
    initial: 600
    step: 5
  inverter_1_overall_factor:
    name: "Inverter #1 Overall Factor"
    min: 98
    max: 102
    step: 0.2
  ## --------------------
  ## Inverter #2 Settings
  inverter_2_operating_voltage_l1:
    name: "Inverter #2 Operating Voltage L1"
    min: 90
    max: 560
    initial: 360
    step: 5
  inverter_2_operating_voltage_m1:
    name: "Inverter #2 Operating Voltage M1"
    min: 140
    max: 980
    initial: 600
    step: 5
  inverter_2_operating_voltage_mb0:
    name: "Inverter #2 Operating Voltage MB0"
    min: 200
    max: 1000
    initial: 600
    step: 5
  inverter_2_overall_factor:
    name: "Inverter #2 Overall Factor"
    min: 98
    initial: 100
    max: 102
    step: 0.2
  ## ------------------
  ## Battery Efficiency
  battery_rated_capacity:
    name: "Battery Rated Capacity (in kWh)"
    min: 5
    max: 30
    initial: 15
    step: 5
  battery_efficiency_soc_trigger:
    name: "Battery Efficiency SOC Trigger (Recomended Set 50%)"
    min: 0
    max: 100
    initial: 50
    step: 5
  battery_efficiency_start_value_charge:
    name: "Battery Efficiency Start Value Charge (in kW)"
    min: 0
    # LUNA S1 7/14/21kWh - 2 inverters with 4 ESS each (8 x 21kWh) = 168kWh
    max: 168
    step: 0.001
    mode: box
  battery_efficiency_start_value_discharge:
    name: "Battery Efficiency Start Value Disharge (in kW)"
    min: 0
    max: 168
    # HA history gives users a 3 digital value, that the instructions say to enter
    step: 0.01
    mode: box
  ## ------------
  ## Solar Panels
  panels_on_inverter_1:
    name: "Panels on Inverter #1"
    min: 0
    max: 50
    step: 1
    mode: box
  panels_on_inverter_2:
    name: "Panels on Inverter #2"
    min: 0
    max: 50
    step: 1
    mode: box
  panels_rated_wp:
    name: "Panels Rated Wp"
    min: 100
    max: 999
    step: 1
    mode: box
# ------------
# INPUT SELECT
# ------------
input_select:
  # -----------------
  # Inverter #1 Setup
  inverter_1_1phase_models:
    name: "Inverter #1 1phase Models"
    options:
      - Select
      - SUN2000 2 KTL-L1
      - SUN2000 3 KTL-L1
      - SUN2000 3.68 KTL-L1
      - SUN2000 4 KTL-L1
      - SUN2000 4.6 KTL-L1
      - SUN2000 5 KTL-L1
      - SUN2000 6 KTL-L1
  inverter_1_3phase_models:
    name: "Inverter #1 3phase Models"
    options:
      - Select
      - SUN2000 3 KTL-M1
      - SUN2000 4 KTL-M1
      - SUN2000 5 KTL-M1
      - SUN2000 6 KTL-M1
      - SUN2000 8 KTL-M1
      - SUN2000 10 KTL-M1
      - SUN2000 12 KTL-MB0
      - SUN2000 15 KTL-MB0
      - SUN2000 17 KTL-MB0
      - SUN2000 20 KTL-MB0
      - SUN2000 25 KTL-MB0
  # -----------------
  # Inverter #2 Setup
  inverter_2_1phase_models:
    name: "Inverter #2 1phase Models"
    options:
      - Select
      - SUN2000 2 KTL-L1
      - SUN2000 3 KTL-L1
      - SUN2000 3.68 KTL-L1
      - SUN2000 4 KTL-L1
      - SUN2000 4.6 KTL-L1
      - SUN2000 5 KTL-L1
      - SUN2000 6 KTL-L1
  inverter_2_3phase_models:
    name: "Inverter #2 3phase Models"
    options:
      - Select
      - SUN2000 3 KTL-M1
      - SUN2000 4 KTL-M1
      - SUN2000 5 KTL-M1
      - SUN2000 6 KTL-M1
      - SUN2000 8 KTL-M1
      - SUN2000 10 KTL-M1
      - SUN2000 12 KTL-MB0
      - SUN2000 15 KTL-MB0
      - SUN2000 17 KTL-MB0
      - SUN2000 20 KTL-MB0
      - SUN2000 25 KTL-MB0      
# ----------
# INPUT TEXT
# ----------
input_text:
  ## ------------------
  ## Electricity Prices
  electricity_price_import:
    name: "Electricity Price Import (Energi Data Service by Default)"
  electricity_price_export:
    name: "Electricity Price Export (Energi Data Service - Sale by Default)"
# ---------------
# TEMPLATE SENSOR
# ---------------
template:
  - sensor:
      ## --------------------------------------
      ## Electricity Price for Energy Dashboard
      - name: "Energi Data Service - Negative"
        unique_id: energi_data_service_negative
        unit_of_measurement: DKK/kWh
        state: >
          {{ states('sensor.energi_data_service') | float(0) * (-1) }}
      ## ----------------------------
      ## Tariff on Electricity Export
      - name: "Tariff Export"
        unique_id: tariff_export
        unit_of_measurement: DKK/kWh
        state: >
          {% set energinet_indfoedningstarif = 0.3 %}
          {% set energinet_balancetarif = 0.24 %}
          {% set konstant_indfoedningstarif = 0.5 %}
          {% set jyskenergi_balancetarif = 2.5 %}
            {{ (
            energinet_indfoedningstarif + 
            energinet_balancetarif + 
            konstant_indfoedningstarif + 
            jyskenergi_balancetarif 
            ) / 100 }}
      ## --------------------
      ## Inverter Rated Power
      - name: "Inverter #1 Rated Power"
        unique_id: inverter_1_rated_power
        unit_of_measurement: W
        state: >
          {% if is_state('input_boolean.inverter_1_1phase','on') %}
            {% if is_state('input_select.inverter_1_1phase_models','SUN2000 2 KTL-L1') %}
              {{ 2000 }}
            {% elif is_state('input_select.inverter_1_1phase_models','SUN2000 3 KTL-L1') %}
              {{ 3000 }}
            {% elif is_state('input_select.inverter_1_1phase_models','SUN2000 3.68 KTL-L1') %}
              {{ 3680 }}
            {% elif is_state('input_select.inverter_1_1phase_models','SUN2000 4 KTL-L1') %}
              {{ 4000 }}
            {% elif is_state('input_select.inverter_1_1phase_models','SUN2000 4.6 KTL-L1') %}
              {{ 4600 }}
            {% elif is_state('input_select.inverter_1_1phase_models','SUN2000 5 KTL-L1') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_1_1phase_models','SUN2000 6 KTL-L1') %}
              {{ 6000 }}
            {% endif %}
          {% elif is_state('input_boolean.inverter_1_3phase','on') %}
            {% if is_state('input_select.inverter_1_3phase_models','SUN2000 3 KTL-M1') %}
              {{ 3000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 4 KTL-M1') %}
              {{ 4000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 5 KTL-M1') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 6 KTL-M1') %}
              {{ 6000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 8 KTL-M1') %}
              {{ 8000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 10 KTL-M1') %}
              {{ 10000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 12 KTL-MB0') %}
              {{ 12000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 15 KTL-MB0') %}
              {{ 15000 }}              
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 17 KTL-MB0') %}
              {{ 17000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 20 KTL-MB0') %}
              {{ 20000 }}              
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 25 KTL-MB0') %}
              {{ 25000 }}
            {% endif %}
          {% else %}
            {{ 0 }}
          {% endif %}
      - name: "Inverter #2 Rated Power"
        unique_id: inverter_2_rated_power
        unit_of_measurement: W
        state: >
          {% if is_state('input_boolean.inverter_2_1phase','on') %}
            {% if is_state('input_select.inverter_2_1phase_models','SUN2000 2 KTL-L1') %}
              {{ 2000 }}
            {% elif is_state('input_select.inverter_2_1phase_models','SUN2000 3 KTL-L1') %}
              {{ 3000 }}
            {% elif is_state('input_select.inverter_2_1phase_models','SUN2000 3.68 KTL-L1') %}
              {{ 3680 }}
            {% elif is_state('input_select.inverter_2_1phase_models','SUN2000 4 KTL-L1') %}
              {{ 4000 }}
            {% elif is_state('input_select.inverter_2_1phase_models','SUN2000 4.6 KTL-L1') %}
              {{ 4600 }}
            {% elif is_state('input_select.inverter_2_1phase_models','SUN2000 5 KTL-L1') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_2_1phase_models','SUN2000 6 KTL-L1') %}
              {{ 6000 }}
            {% endif %}
          {% elif is_state('input_boolean.inverter_2_3phase','on') %}
            {% if is_state('input_select.inverter_2_3phase_models','SUN2000 3 KTL-M1') %}
              {{ 3000 }}
            {% elif is_state('input_select.inverter_2_3phase_models','SUN2000 4 KTL-M1') %}
              {{ 4000 }}
            {% elif is_state('input_select.inverter_2_3phase_models','SUN2000 5 KTL-M1') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_2_3phase_models','SUN2000 6 KTL-M1') %}
              {{ 6000 }}
            {% elif is_state('input_select.inverter_2_3phase_models','SUN2000 8 KTL-M1') %}
              {{ 8000 }}
            {% elif is_state('input_select.inverter_2_3phase_models','SUN2000 10 KTL-M1') %}
              {{ 10000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 12 KTL-MB0') %}
              {{ 12000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 15 KTL-MB0') %}
              {{ 15000 }}              
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 17 KTL-MB0') %}
              {{ 17000 }}
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 20 KTL-MB0') %}
              {{ 20000 }}              
            {% elif is_state('input_select.inverter_1_3phase_models','SUN2000 25 KTL-MB0') %}
              {{ 25000 }}
            {% endif %}
          {% else %}
            {{ 0 }}
          {% endif %}

```
