### DISCUSSION TITLE
Automate Invereter (Huawei / iStore in AU) Detection and Configuration

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [JensenNick/huawei_solar_pees#49] [Forum]
Hi @JensenNick 

I'm still trying to get time to see where this would mean updating the processes from input selectors and/or automations etc to define the inverter, but here is the code you can use to:

Sensor to publish the inverter model you have. This will report in the format of SUN2000-6KTL-M1 / SUN2000-5KTL-L1 etc:

Edit: Updated to detect either Huawei L1 / M1 / MB0 (being format: SUN2000-5KTL-L1 / SUN2000-6KTL-M1 / SUN2000-12KTL-MB0) or the iStore (OEM) variants (format: IS-HYB-5000-1PH / IS-HYB-6000-1PH / IS-HYB-5000-3PH / IS-HYB-6000-3PH.. if the MB0 are sold as IS-HYB-12000/17000/20000/25000-3PH this regex will already support them).

Edited 16 April 2024: Added the ability to determine how many batteries (stacks) are installed and the overall 'Rated Capacity' of the batteries installed (required WLCRS v1.40A2 or higher, that provides sensors for 'batteries' as well as 'battery_1_xxx' 'battery_2_xxx' etc.

```

template:
##########################################################
#
#   Detects if there is a Huawei L0, L1, M1, MB0 or iStore
#   1PH or 3PH inverter, and publishes its model number.
#
  - sensor:
    - name: "Inverter 1 - Model"
      unique_id: inverter_1_model
      icon: phu:huawei-solar-inverter
      state: >-
        {{ device_attr("sensor.inverter_input_power", "model") | regex_findall_index('(SUN\d+-\d+KTL-[L|M|MB]\d+)|(IS-HYB-\d-\[1|3]PH)', 0) | first }}
      availability: >-
        {{  (states('sensor.inverter_input_power') not in [ 'unknown', 'unavailable', 'none' ] ) }}

  - sensor:
    - name: "Inverter 2 - Model"
      unique_id: inverter_2_model
      icon: phu:huawei-solar-inverter
      state: >-
        {{ device_attr("sensor.inverter_input_power_2", "model") | regex_findall_index('(SUN\d+-\d+KTL-[L|M|MB]\d+)|(IS-HYB-\d-\[1|3]PH)', 0) | first }}
      availability: >-
        {{  (states('sensor.inverter_input_power_2') not in [ 'unknown', 'unavailable', 'none' ] ) }}


##########################################################
#
#   Detects if there is a Battery attached to either inverter
#   and publishes the total number of batteries (stacks), up to 4.
#

  - sensor:
    - name: "Battery 1 - Model"
      unique_id: battery_1_model
      icon: phu:solar-battery-15
      state: >-
        {% set device_model = device_attr('sensor.battery_1_state_of_capacity', 'model') %}
        {% if device_model == none %}
          Not Installed
        {% else %}
          {{ device_model }}
        {% endif %}


  - sensor:
    - name: "Battery 2 - Model"
      unique_id: battery_2_model
      icon: phu:solar-battery-15
      state: >-
        {% set device_model = device_attr('sensor.battery_2_state_of_capacity', 'model') %}
        {% if device_model == none %}
          Not Installed
        {% else %}
          {{ device_model }}
        {% endif %}


  - sensor:
    - name: "Battery 3 - Model"
      unique_id: battery_3_model
      icon: phu:solar-battery-15
      state: >-
        {% set device_model = device_attr('sensor.battery_3_state_of_capacity', 'model') %}
        {% if device_model == none %}
          Not Installed
        {% else %}
          {{ device_model }}
        {% endif %}


  - sensor:
    - name: "Battery 4 - Model"
      unique_id: battery_4_model
      icon: phu:solar-battery-15
      state: >-
        {% set device_model = device_attr('sensor.battery_4_state_of_capacity', 'model') %}
        {% if device_model == none %}
          Not Installed
        {% else %}
          {{ device_model }}
        {% endif %}
      

##########################################################
#
#   Uses the 'Model' sensors above, to count the number of 
#   battery stacks (not cells) installed in the site.
#

  - sensor:
    - name: "Batteries - Installed"
      unique_id: batteries_installed
      icon: phu:solar-battery-15
      state: >-
        {% set battery_sensors = [
          states('sensor.battery_1_model'),
          states('sensor.battery_2_model'),
          states('sensor.battery_3_model'),
          states('sensor.battery_4_model')
        ] %}
        {% set installed_batteries = battery_sensors | reject('in', ['unknown', 'unavailable', 'none', 'Not Installed']) | list %}
        {{ installed_batteries | count }}



##########################################################
#
#  Uses the 'Diagnostic: Energy' sensor for each battery CELL
#  to calculate the total rated capacity (size) of the batteries
#  installed, up to 4 battery stacks (12 cells).
#
#  The output is divided by 1,000 to convert from Watts to kWh
#
#
  - sensor:
    - name: "Batteries - Rated Capacity"
      unique_id: batteries_rated_capacity
      unit_of_measurement: kWh
      device_class: power
      state_class: measurement      
      icon: mdi:battery-charging-100
      state: >-
        {% set battery_1_energy = (states('sensor.battery_1_energy') | float if states('sensor.battery_1_energy') not in ['unknown', 'unavailable', 'none'] else 0) +
                                  (states('sensor.battery_1_energy_2') | float if states('sensor.battery_1_energy_2') not in ['unknown', 'unavailable', 'none'] else 0) +
                                  (states('sensor.battery_1_energy_3') | float if states('sensor.battery_1_energy_3') not in ['unknown', 'unavailable', 'none'] else 0) %}
        {% set battery_2_energy = (states('sensor.battery_2_energy') | float if states('sensor.battery_2_energy') not in ['unknown', 'unavailable', 'none'] else 0) +
                                  (states('sensor.battery_2_energy_2') | float if states('sensor.battery_2_energy_2') not in ['unknown', 'unavailable', 'none'] else 0) +
                                  (states('sensor.battery_2_energy_3') | float if states('sensor.battery_2_energy_3') not in ['unknown', 'unavailable', 'none'] else 0) %}
        {% set battery_3_energy = (states('sensor.battery_3_energy') | float if states('sensor.battery_3_energy') not in ['unknown', 'unavailable', 'none'] else 0) +
                                  (states('sensor.battery_3_energy_2') | float if states('sensor.battery_3_energy_2') not in ['unknown', 'unavailable', 'none'] else 0) +
                                  (states('sensor.battery_3_energy_3') | float if states('sensor.battery_3_energy_3') not in ['unknown', 'unavailable', 'none'] else 0) %}
        {% set battery_4_energy = (states('sensor.battery_4_energy') | float if states('sensor.battery_4_energy') not in ['unknown', 'unavailable', 'none'] else 0) +
                                  (states('sensor.battery_4_energy_2') | float if states('sensor.battery_4_energy_2') not in ['unknown', 'unavailable', 'none'] else 0) +
                                  (states('sensor.battery_4_energy_3') | float if states('sensor.battery_4_energy_3') not in ['unknown', 'unavailable', 'none'] else 0) %}
        {{ (( battery_1_energy + battery_2_energy + battery_3_energy + battery_4_energy) / 1000 ) | round(0) }}


##########################################################
#
# Home Assistant Records Service.
# excludes the follow sensors from being recorded:
#

recorder:
  exclude:
    entities:
      - sensor.inverter_1_model
      - sensor.inverter_2_model
      - sensor.battery_1_model
      - sensor.battery_2_model
      - sensor.battery_3_model
      - sensor.battery_4_model
      - sensor.batteries_number_installed
      - sensor.batteries_rated_capacity
```

If your using the yaml that allows replicating a copy of the sensors from your Production HA (that has WLCRS and your Inverters linked to it) across to a Development instance of HA with PESS etc, here's the yaml you'll need to add to it. Just remember to update the IP and Long Term Token Key to your instances details:

EDIT: Here's the whole yaml. As per https://github.com/JacobsenKim/ha_huawei_solar_replicate (but with more sensors).

@JacobsenKim JacobsenKim

```
################################################################################################
# Replica power sensor, read from source, from target to show on target Home Assistant instance.
# huawei_solar_replicate: v1.0.0
#
# Link: https://github.com/JacobsenKim/ha_huawei_solar_replicate
# How2: https://github.com/JacobsenKim/ha_huawei_solar_replicate/wiki
#
################################################################################################
#
##########################################################################
## !!!!!! Always make sure to back up everything before you begin !!!!! ##
##########################################################################
#
# Replica sensors =
#
# sensor.inverter_input_power (from the Huawei Solar integration)
# sensor.inverter_input_power_2 (from the Huawei Solar integration)
# sensor.inverter_active_power (from the Huawei Solar integration)
# sensor.power_meter_active_power (from the Huawei Solar integration)
# sensor.power_meter_consumption (from the Huawei Solar integration)
# sensor.battery_charge_discharge_power (from the Huawei Solar integration)
# sensor.battery_state_of_capacity (from the Huawei Solar integration)
# sensor.power_meter_exported (from the Huawei Solar integration)
# sensor.battery_day_charge (from the Huawei Solar integration)
# sensor.battery_day_discharge (from the Huawei Solar integration)
# sensor.inverter_daily_yield  (from the Huawei Solar integration)
#
############################################################################
## Replace to fit your info:  ( ip, Authorization token, scan_interval ) ##
############################################################################
############################################################################
## Replace to fit your info:  ( ip, Authorization token, scan_interval ) ##
############################################################################
############################################################################
## Replace to fit your info:  ( ip, Authorization token, scan_interval ) ##
############################################################################
#
sensor:

# sensor.inverter_1_model
  - platform: rest
    name: "Inverter 1 - Model"
    unique_id: "inverter_1_model"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_1_model"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN"
      Content-Type: "application/json"
    value_template: "{{ value_json.state }}"
    scan_interval: 30
    icon: mdi:solar-power

# sensor.inverter_2_model
  - platform: rest
    name: "Inverter 2 - Model"
    unique_id: "inverter_2_model"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_2_model"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN"
      Content-Type: "application/json"
    value_template: "{{ value_json.state }}"
    scan_interval: 30
    icon: mdi:solar-power



# sensor.inverter_input_power
  - platform: rest
    name: "Inverter Input Power"
    unique_id: "inverter_input_power"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_input_power"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN"
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_input_power_2
  - platform: rest
    name: "Inverter Input Power 2"
    unique_id: "inverter_input_power_2"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_input_power_2"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_active_power
  - platform: rest
    name: "Inverter Active Power"
    unique_id: "inverter_active_power"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_active_power_2
  - platform: rest
    name: "Inverter Active Power 2"
    unique_id: "inverter_active_power_2"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_pv_1_voltage
  - platform: rest
    name: "Inverter - PV 1 Voltage"
    unique_id: inverter_pv_1_voltage
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:lightening-bolt-outline
    unit_of_measurement: "V"
    state_class: "measurement"
    device_class: voltage


# sensor.inverter_pv_2_voltage
  - platform: rest
    name: "Inverter - PV 2 Voltage"
    unique_id: inverter_pv_2_voltage
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:lightening-bolt-outline
    unit_of_measurement: "V"
    state_class: "measurement"
    device_class: voltage


# sensor.inverter_pv_1_voltage_2
  - platform: rest
    name: "Inverter - PV 1 Voltage 2"
    unique_id: inverter_pv_1_voltage_2
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:lightening-bolt-outline
    unit_of_measurement: "V"
    state_class: "measurement"
    device_class: voltage


# sensor.inverter_pv_2_voltage_2
  - platform: rest
    name: "Inverter - PV 2 Voltage 2"
    unique_id: inverter_pv_2_voltage_2
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 10
    icon: mdi:lightening-bolt-outline
    unit_of_measurement: "V"
    state_class: "measurement"
    device_class: voltage


# sensor.power_meter_active_power
  - platform: rest
    name: "Power Meter Active Power"
    unique_id: "power_meter_active_power"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.power_meter_active_power"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.power_meter_consumption
  - platform: rest
    name: "Power Meter Consumption"
    unique_id: "power_meter_consumption"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.power_meter_consumption"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.battery_charge_discharge_power
  - platform: rest
    name: "Battery Charge Discharge Power"
    unique_id: "battery_charge_discharge_power"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.battery_charge_discharge_power"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:home-battery-outline
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.battery_state_of_capacity
  - platform: rest
    name: "Battery State Of Capacity"
    unique_id: "battery_state_of_capacity"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.battery_state_of_capacity"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:home-battery
    unit_of_measurement: "%"
    state_class: "measurement"

# sensor.power_meter_exported
  - platform: rest
    name: "Power Meter Exported"
    unique_id: "power_meter_exported"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.power_meter_exported"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:flash
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.battery_day_charge
  - platform: rest
    name: "Battery Day Charge"
    unique_id: "battery_day_charge"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.battery_day_charge"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:battery-plus-variant
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.battery_day_discharge
  - platform: rest
    name: "Battery Day Discharge"
    unique_id: "battery_day_discharge"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.battery_day_discharge"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:battery-minus-variant
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.inverter_daily_yield
  - platform: rest
    name: "Inverter Daily Yield"
    unique_id: "inverter_daily_yield"
    resource: "http://YOUR-SOURCE-IP:8123/api/states/sensor.inverter_daily_yield"
    method: GET
    headers:
      Authorization: "Bearer LONG-TERM-TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:solar-power
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

```
