### DISCUSSION TITLE
Any users of SUN2000 3.68 or 4.6 KTL-L1?

### DISCUSSION THREAD

**Discussion by JensenNick** [JensenNick/huawei_solar_pees#85] [Announcements]
Please help us to determine the output for these inverter models. Is it SUN2000-368KTL / -46KTL or maybe -3-68KTL / -4-6KTL or something else? Copy/paste this code into your Template tool in Developer tools and let us know the output. Thanks!

```yaml
{{ device_attr("sensor.inverter_input_power","model") | regex_findall_index('(SUN\d+-\d+(KTL|K)-(L|LC|M|MB|MAP)\d)|(IS-HYB-\d+-[1|3]PH)', 0) | first }}
```

**Comment by Mahai17** [comment]
IndexError: list index out of range
I wonder, because there is no attribute like "model" in the "sensor.inverter_input_power" entity. 
<img width="986" alt="image" src="https://github.com/user-attachments/assets/574caf42-0cab-4fb8-99f3-80cef07da77e">

**Reply by JensenNick** [reply]
Which version of the Huawei Solar integration are you running? You have to be on version 1.5.0a1 (beta) in order to have this to work.

**Reply by Mahai17** [reply]
I was on latest non-beta.
Now I upgraded to 1.5.0a1
But still not working. There is still no attribute "model" in entity "sensor.inverter_input_power". 
<img width="613" alt="image" src="https://github.com/user-attachments/assets/53d7a7a6-8bd8-46e1-b658-7bc9043803c7">
<img width="943" alt="image" src="https://github.com/user-attachments/assets/ba77feea-b386-4b94-94cb-0c55d208c100">

**Reply by JensenNick** [reply]
Please try to run the code provided in the Developer tool.

**Reply by Mahai17** [reply]
Still the same: IndexError: list index out of range
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/4d0c66fd-f7a2-4f5a-a5db-dd428d3cb327">

**Reply by JensenNick** [reply]
...and you did restart?

**Reply by Mahai17** [reply]
Maybe I am wrong, but the code can not succeed, because there is no attribute "model" in entity "sensor.inverter_input_power".
Or do I  miss anything?

**Reply by Mahai17** [reply]
Yes, I restarted. See Version Info in screenshot above.

**Reply by JensenNick** [reply]
I dont have the attribute in the sensor either. I had @Roving-Ronin come up with the code for retrieving the inverter model. Maybe it is so simple that "d+" doesn't recognize a decimal number. Could you try with this...

```yaml
{{ device_attr("sensor.inverter_input_power","model") | regex_findall_index('(SUN\d+-\d+.d+(KTL|K)-(L|LC|M|MB|MAP)\d)|(IS-HYB-\d+-[1|3]PH)', 0) | first }}
```

**Reply by Mahai17** [reply]
IndexError: list index out of range

**Reply by Mahai17** [reply]
I tried this one: {{ device_attr("sensor.inverter_input_power","model") }}
==> SUN2000-4.6KTL-L1

**Reply by Mahai17** [reply]
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/1f92ed4d-9c17-4579-89ca-6edcb08c83c6">

**Reply by JensenNick** [reply]
Yes, but we need to correct the regex lookup to be able to read the inverter model (and only the relevant part). I'll get back to you...

**Reply by JensenNick** [reply]
Could you try this...?
```yaml
{{ device_attr("sensor.inverter_input_power","model") | regex_findall_index('(SUN\d+\.?\d*-\d+\.?\d*(KTL|K)-(L|LC|M|MB|MAP)\d)|(IS-HYB-\d+\.?\d*-[1|3]PH)', 0) | first }}
```

**Reply by Mahai17** [reply]
Output: SUN2000-4.6KTL-L1

**Reply by JensenNick** [reply]
The *"Huawei Solar PEES package"* has now been updated to support the SUN2000 4.6KTL-L1 and SUN2000 3.68KTL-L1.

**Reply by Mahai17** [reply]
Works now. Thank you.
One question. I used to use sensor.power_inverter_1_input. Which one should I use with efficiency correction?

**Reply by JensenNick** [reply]
I guess your inverter will be picked up as inverter #1 and there has not been made changes to the naming, so `sensor.power_inverter_1_input` will work both with the efficiency correction deactivated and activated. Maybe I should ad a condition for displaying the card for Inverter #2.

**Reply by JensenNick** [reply]
You could try to copy/past this into your input card. Here the Inverter #2 is conditional, so you shouldn't even se it / have it as an option. Let me know if it works / can't test it myself :-)...

```yaml
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: input_boolean.efficiency_corrected_power_input
    title: Enable / Disable PEES Functions
    show_header_toggle: false
  - type: entities
    entities:
      - entity: sensor.inverter_1_model
    title: "Inverter #1"
  - type: conditional
    conditions:
      - condition: state
        entity: input_boolean.efficiency_corrected_power_input
        state: "on"
    card:
      type: vertical-stack
      cards:
        - type: conditional
          conditions:
            - condition: state
              entity: binary_sensor.inverter_1_is_l1
              state: "on"
          card:
            type: entities
            entities:
              - entity: input_number.inverter_1_operating_voltage_l1
              - entity: input_number.inverter_1_overall_factor
        - type: conditional
          conditions:
            - condition: state
              entity: binary_sensor.inverter_1_is_m1
              state: "on"
          card:
            type: entities
            entities:
              - entity: input_number.inverter_1_operating_voltage_m1
              - entity: input_number.inverter_1_overall_factor
        - type: entities
          entities:
            - entity: sensor.inverter_pv_1_voltage
            - entity: sensor.inverter_pv_2_voltage
  - type: conditional
    conditions:
      - condition: state
        entity: sensor.inverter_2_model
        state_not: unavailable
      - condition: state
        entity: sensor.inverter_2_model
        state_not: unknown
    card:
      type: entities
      entities:
        - entity: sensor.inverter_2_model
      title: "Inverter #2"
  - type: conditional
    conditions:
      - condition: state
        entity: input_boolean.efficiency_corrected_power_input
        state: "on"
      - condition: state
        entity: sensor.inverter_2_model
        state_not: unavailable
      - condition: state
        entity: sensor.inverter_2_model
        state_not: unknown
    card:
      type: vertical-stack
      cards:
        - type: conditional
          conditions:
            - condition: state
              entity: binary_sensor.inverter_2_is_l1
              state: "on"
          card:
            type: entities
            entities:
              - entity: input_number.inverter_2_operating_voltage_l1
              - entity: input_number.inverter_2_overall_factor
        - type: conditional
          conditions:
            - condition: state
              entity: binary_sensor.inverter_2_is_m1
              state: "on"
          card:
            type: entities
            entities:
              - entity: input_number.inverter_2_operating_voltage_m1
              - entity: input_number.inverter_2_overall_factor
        - type: entities
          entities:
            - entity: sensor.inverter_pv_1_voltage_2
            - entity: sensor.inverter_pv_2_voltage_2
  - type: entities
    entities:
      - entity: input_text.electricity_price_import
      - entity: input_text.electricity_price_export
      - entity: input_text.electricity_price_ev_charging
    title: Electricity Price
```
