### ISSUE TITLE
Energy Meter vs Utility Meter

### ISSUE THREAD

**Issue by Roving-Ronin** [JensenNick/huawei_solar_pees#2]
Hi @JensenNick 

Whilst my electricity retails cost plans are a lot simpler, based upon Time of Use (TOU), looking at the heap of sensors you've ended up creating to try and track the amount (kWh) of power used, the tariff rate (kWh and $/kWh) used and then days/months/years etc for all that. I thought you still might be interested in looking at the 'energy_meter:" options, that provides the same functions as 'utility_meter', but also allows for easily having it automatically add extra sensors that track all the meters you setup.

See: https://github.com/zeronounours/HA-custom-component-energy-meter

For example, here's my 'huawei_solar_electricity_costs.yaml' file [huawei_solar_electricity_costs.yaml.txt](https://github.com/JensenNick/huawei_solar_pees/files/13463656/huawei_solar_electricity_costs.yaml.txt) , that contains a sensor that publishes "the" current price for the power I'm importing.  An additional one could be defined if Grid Exports where paid at different times of the day, but I don't have this so I just use the "price: 0.07" ($0.07) option in the Energy Meter.  Alternatively your Energi integration I assume publishes such a sensor that supplies the live import or export prices for you? That could simply be called in the Energy_Meter using the 'source:  sensor.your-power-import-price' or 'source: sensor.your-export-power-price'

Whilst I have Daily / Monthly / Yearly Import and Export meters, and then auto generated meters based upon the tariff (so I also see the kWh and $ for each tariff period, not just the Daily/Monthly/Yearly), using the daily for examples:

![image](https://github.com/JensenNick/huawei_solar_pees/assets/108674933/aeb90fbb-3829-4fef-a7e2-9b2e12b38dd1)

![image](https://github.com/JensenNick/huawei_solar_pees/assets/108674933/a1ea0fdc-6288-44ef-9eb0-fb26e636f196)

Is created by this amount of yaml:

```
#########################
# EXPORT ENERGY METERS
# See: https://github.com/zeronounours/HA-custom-component-energy-meter

  hs_power_exported_daily:
    unique_id: hs_power_exported_daily
    name: HS Power - Exported Daily
    source: sensor.power_meter_exported
    cycle: daily
    price: 0.07

  hs_power_exported_monthly:
    unique_id: hs_power_exported_monthly
    name: HS Power - Exported Monthly
    source: sensor.power_meter_exported
    cycle: monthly
    price: 0.07

  hs_power_exported_yearly:
    unique_id: hs_power_exported_yearly
    name: HS Power - Exported Yearly
    source: sensor.power_meter_exported
    cycle: yearly
    price: 0.07
#########################
```

The 18 different energy_meters to track all daily/monthly/yearly and then the Peak / Shoulder / Off-Peak tariff periods and costs are created by this few lines of yaml:

```
####################################
# IMPORT UTILITY METERS
#

energy_meter:

  hs_power_imported_daily:
    unique_id: hs_power_imported_daily
    name: HS Power Imported - Daily
    source: sensor.power_meter_consumption
    cycle: daily
    price_entity: &entity-price sensor.electricity_price
    tariffs:
      - peak
      - shoulder
      - offpeak

  hs_power_imported_monthly:
    unique_id: hs_power_imported_monthly
    name: HS Power Imported - Monthly
    source: sensor.power_meter_consumption
    cycle: monthly
    price_entity: *entity-price
    tariffs:
      - peak
      - shoulder
      - offpeak

  hs_power_imported_yearly:
    unique_id: hs_power_imported_yearly
    name: HS Power Imported - Yearly
    source: sensor.power_meter_consumption
    cycle: yearly
    price_entity: *entity-price
    tariffs:
      - peak
      - shoulder
      - offpeak

```

The daily / monthly / yearly energy_meters tracking the kWh and $ , are created using this code, that just groups each of those periods Peak + Shoulder + Off Peak energy meters to create SUM total amounts for the Day/Week/Year.  Code is:

![image](https://github.com/JensenNick/huawei_solar_pees/assets/108674933/9a06af9e-1f87-429a-8a68-992984bdae9c)

![image](https://github.com/JensenNick/huawei_solar_pees/assets/108674933/348b9634-796b-4c19-b940-cb60a9d67c45)

```
#########################
#
# GROUP - TO SUM UP THE DAILY / MONTHLY / YEARLY IMPORT KWH and $ SENSORS
#         TO GIVE A TOTAL OF EACH
#

sensor:

# DAILY
  - platform: group
    name: HS Power Imported - Daily Total kWh
    unique_id: hs_power_imported_daily_total_kwh
    type: sum
    entities:
      - sensor.hs_power_imported_daily_peak
      - sensor.hs_power_imported_daily_shoulder
      - sensor.hs_power_imported_daily_offpeak

  - platform: group
    name: HS Power Imported - Daily Total Cost
    unique_id: hs_power_imported_daily_total_cost
    type: sum
    entities:
      - sensor.hs_power_imported_daily_cost_peak
      - sensor.hs_power_imported_daily_cost_shoulder
      - sensor.hs_power_imported_daily_cost_offpeak

# MONTHLY
  - platform: group
    name: HS Power Imported - Monthly Total kWh
    unique_id: hs_power_imported_monthly_total_kwh
    type: sum
    entities:
      - sensor.hs_power_imported_monthly_peak
      - sensor.hs_power_imported_monthly_shoulder
      - sensor.hs_power_imported_monthly_offpeak

  - platform: group
    name: HS Power Imported - Monthly Total Cost
    unique_id: hs_power_imported_monthly_total_cost
    type: sum
    entities:
      - sensor.hs_power_imported_monthly_cost_peak
      - sensor.hs_power_imported_monthly_cost_shoulder
      - sensor.hs_power_imported_monthly_cost_offpeak

# YEARLY
  - platform: group
    name: HS Power Imported - Yearly Total kWh
    unique_id: hs_power_imported_yearly_total_kwh
    type: sum
    entities:
      - sensor.hs_power_imported_yearly_peak
      - sensor.hs_power_imported_yearly_shoulder
      - sensor.hs_power_imported_yearly_offpeak

  - platform: group
    name: HS Power Imported - Yearly Total Cost
    unique_id: hs_power_imported_yearly_total_cost
    type: sum
    entities:
      - sensor.hs_power_imported_yearly_cost_peak
      - sensor.hs_power_imported_yearly_cost_shoulder
      - sensor.hs_power_imported_yearly_cost_offpeak

```
Then to get HA to automatically update which energy_meter its using based upon the time of the day (I also use something like this, but based upon the MJ of gas used in the Quarter, to update the tariff plan being used (i.e. 0 - 1800MJ = rate 1, 1801 - 100000MJ = rate 2 etc).

```
#######################
#
# Checks the time and based upon TOU rate times, updates the 'hs_power_imported_daily/monthly/yearly' entities to use Peak / Shoulder / OffPeak tariff
#

automation:
### adjust the time triggers below to match when your standard electricity tariff changes (peak, shoulder, offpeak). Adjust the template in the action block as required to match your plan.
  - alias: Set Electricity Tariff
    description: 'Set Electricity Tariff (Huawei Solar) depending upon the day of week and time'
    trigger:
      - platform: time
        at: '07:00:30'
      - platform: time
        at: '09:00:30'
      - platform: time
        at: '17:00:30'
      - platform: time
        at: '20:00:30'
      - platform: time
        at: '22:00:30'
      - platform: homeassistant
        event: start
    condition: []
    action:
      - service: select.select_option
        data:
          option: >-
            {% set t = now() %}
            {%- if (( t.hour >= 7 and t.hour < 9 ) or ( t.hour >= 17 and t.hour < 20 )) and
            is_state('binary_sensor.workday_sensor', 'on') %}
              peak
            {%- elif (( t.hour >= 9 and t.hour < 17 ) or ( t.hour >= 20 and t.hour < 22 )) and 
            is_state('binary_sensor.workday_sensor', 'on') %}
              shoulder
            {%- else -%}
              offpeak
            {%- endif -%}
        target:
          entity_id:
#  Selectors used by utility_meter / energy_meter
            - select.hs_power_imported_daily
            - select.hs_power_imported_monthly
            - select.hs_power_imported_yearly
    mode: single
```
