### ISSUE TITLE
Utility Meters "jumping"

### ISSUE THREAD

**Issue by JensenNick** [JensenNick/huawei_solar_pees#66]
Under certain circumstances (which I still haven't identified) the ultility meters `sensor.economy_nri_pv` and `sensor.economy_nri_battery` introduce a significant "jump" in value. This also includes the related sensors with a cycle but not the (ts) input sensor.
![2024-08-27_09-20-45](https://github.com/user-attachments/assets/925488bf-2450-4bf4-b908-39d54cecc68c)

```
  economy_nri_pv:
    source: sensor.economy_nri_pv_ts
    name: "Economy - NRI PV"
    unique_id: economy_nri_pv
    net_consumption: true
```
and
```
  economy_nri_battery:
    source: sensor.economy_nri_battery_ts
    name: "Economy - NRI Battery"
    unique_id: economy_nri_battery
    net_consumption: true
```
My time to update/support/investigate is limited at the moment, but it could be one of the settings of the utility meter which is wrong/missing [https://www.home-assistant.io/integrations/utility_meter/](url)

**Comment by JensenNick** [comment]
This issue has been resolved with the release of v2.1.2.

**Comment by JensenNick** [comment]
This issue persists althogh this time it was my utility_meters based on sensor.energy_yield_total_ts that behaved.
![2024-10-09_16-51-18](https://github.com/user-attachments/assets/6ec8a970-4846-451b-99a7-d413d417d2f8)

I'm now testing if this correction will prevent the issue... "float(0)" changes to "float" for sensors with availability and an if-rule for sensor.energy_yield_2_ts. The challenge here is to incorporate a value for the 2nd inverter in those use-cases with only one inverter and not to have the sensor reset to "0".

```yaml
      ## ----------------------------------
      ## Huawei Solar PEES - Energy Sensors
      - name: "Energy Yield #1 (ts)"
        unique_id: energy_yield_1_ts
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: >
          {{ states('sensor.energy_yield_1') | float }}
        availability: >
          {{ has_value('sensor.energy_yield_1') }}
      - name: "Energy Yield #2 (ts)"
        unique_id: energy_yield_2_ts
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: >
          {% if has_value('sensor.energy_yield_2') %}
            {{ states('sensor.energy_yield_2') | float }}
          {% else %}
            {{ 0 }}
          {% endif %}
      - name: "Energy Yield Total (ts)"
        unique_id: energy_yield_total_ts
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        state: >
          {{ states('sensor.energy_yield_1') | float +
          states('sensor.energy_yield_2') | float }}
        availability: >
          {{ has_value('sensor.energy_yield_1') and
          has_value('sensor.energy_yield_2') }}
```
Additionally I'm considering the option to ad `periodically_resetting: false` to some/all utility meters. I'd appreciate any input on the issue. Here is what "Claude" has to say...

![2024-10-10_08-29-26](https://github.com/user-attachments/assets/4b6b20ce-e962-440c-8e0f-74c24a3e7724)
